{"name": "Login with invalid data failed with error check", "status": "passed", "description": "Request for a login with invalid data, verify an answer", "start": 1717016038765, "stop": 1717016039070, "uuid": "9cfc77e7-971c-4541-bbf0-134206534baa", "historyId": "2131e485f1f750039daff97279aa7274", "testCaseId": "2131e485f1f750039daff97279aa7274", "fullName": "tests.test_login_courier.TestCourierLogin#test_courier_login_null_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "PC"}, {"name": "thread", "value": "9424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}