{"name": "Login with invalid data failed with error check", "status": "passed", "description": "Request for a login with invalid data, verify an answer", "start": 1716760175778, "stop": 1716760176088, "uuid": "641397f8-0944-4c20-bce1-deb1e4666fdc", "historyId": "2131e485f1f750039daff97279aa7274", "testCaseId": "2131e485f1f750039daff97279aa7274", "fullName": "tests.test_login_courier.TestCourierLogin#test_courier_login_null_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "PC"}, {"name": "thread", "value": "352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}